version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app-net
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
