model_id: gpt2
train_file_path_raw: data/raw/article_train.csv
train_file_path_curated: data/train/article_train.txt
per_device_train_batch_size: 8
output_dir: ""
overwrite_output_dir: false
num_train_epochs: 5
save_steps: 500
